CREATE TABLE User (
  ID INT AUTO INCREMENT PRIMARY KEY ,
  NAME VARCHAR(255) NOT NULL ,
  E-MAIL VARCHAR(255)  NOT NULL ,
  ADMIN VARCHAR(255) NOT NULL ,
  PASSWORD BOOLEAN DEFAULT FALSE,
);

CREATE TABLE G7E (
  Time DATETIME DEFAULT CURRENT_TIMESTAMP ,
  degrees FLOAT, 
);
